# Generated by Django 5.0.7 on 2024-07-14 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('depth', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('barcode', models.CharField(max_length=50)),
                ('qrCode', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('date', models.DateTimeField()),
                ('reviewerName', models.CharField(max_length=255)),
                ('reviewerEmail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discountPercentage', models.FloatField()),
                ('rating', models.FloatField()),
                ('stock', models.IntegerField()),
                ('tags', models.JSONField()),
                ('brand', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('warrantyInformation', models.CharField(max_length=255)),
                ('shippingInformation', models.CharField(max_length=255)),
                ('availabilityStatus', models.CharField(max_length=100)),
                ('returnPolicy', models.CharField(max_length=255)),
                ('minimumOrderQuantity', models.IntegerField()),
                ('images', models.JSONField()),
                ('thumbnail', models.URLField()),
                ('dimensions', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.dimension')),
                ('meta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.meta')),
                ('reviews', models.ManyToManyField(to='products.review')),
            ],
        ),
    ]
